apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: devlab-api
    component: otel-collector
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
    - name: http-otlp
      port: 4318
      targetPort: 4318
