version: '3'
services:
  devlab-api:
    build:
      context: ../
      dockerfile: ./src/Lab.Customers.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
  otel-collector:
    build:
      context: ../
      dockerfile: ./deploy/otel/Dockerfile
    ports:
      - "4317:4317"
      - "4318:4318" 
